### ISSUE TITLE
Failing end-to-end test for returning number of cigarettes

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#258]
the 'get data from tracker' scenario is failing in the end-to-end tests.
```
Failures:

1) Scenario: Get data from tracker # features/trackerdata.feature:3
   ✔ Given rasa bot is up and running # features/step_definitions/agenda_steps.js:56
   ✔ When user is authenticated # features/step_definitions/agenda_steps.js:89
   ✔ Then test user is connected # features/step_definitions/agenda_steps.js:95
   ✔ When users asks for consumed cigarettes # features/step_definitions/agenda_steps.js:187
   ✔ Then the message is addressed to the therapist # features/step_definitions/agenda_steps.js:119
   ✔ When therapist produces a response # features/step_definitions/agenda_steps.js:138
   ✔ Then therapist response is found to be addressed to the user # features/step_definitions/agenda_steps.js:148
   ✖ And therapist responds with the number of tracked cigarettes # features/step_definitions/agenda_steps.js:191
       TypeError: data is not iterable
           at /Users/svenvanderburg/projects/perfectfit/virtual-coach-main/features/step_definitions/agenda_steps.js:208:27
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Probably something wrong in niceday api looking at their logs:
```
Error: ForbiddenError
virtual-coach-main-niceday_api-1     |     at ForbiddenError.SenseError [as constructor] (/app/node_modules/@sense-os/error/index.js:10:19)
virtual-coach-main-niceday_api-1     |     at new ForbiddenError (/app/build/goalie-js/dist/commons/Error.js:72:42)
virtual-coach-main-niceday_api-1     |     at /app/build/goalie-js/dist/commons/HTTPResponse.js:50:32
virtual-coach-main-niceday_api-1     |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
virtual-coach-main-niceday_api-1     |   message: 'You do not have permission to perform this action',
virtual-coach-main-niceday_api-1     |   details: {
virtual-coach-main-niceday_api-1     |     response: Response {
virtual-coach-main-niceday_api-1     |       size: 0,
virtual-coach-main-niceday_api-1     |       timeout: 0,
virtual-coach-main-niceday_api-1     |       [Symbol(Body internals)]: [Object],
virtual-coach-main-niceday_api-1     |       [Symbol(Response internals)]: [Object]
virtual-coach-main-niceday_api-1     |     },
virtual-coach-main-niceday_api-1     |     body: { detail: 'You do not have permission to perform this action.' }
virtual-coach-main-niceday_api-1     |   }
```

**Comment by svenvanderburg** [comment]
I found the problem. It resulted from alphasven therapist not having accepted the connection request from 'test user' yet. If you encounter this problem you need to accept 'test user's connection request in https://alpha.niceday.app/ . Or ask Walter to send this invite if he hasn't done so yet.
